###########################################################
#################### VAMPIR Functions #####################
###########################################################

# This file list the functions used to wrangle the data
# generated by ARIBA.

###########################################################
###########################################################
###########################################################

# Collapses data frame to unique lines while ignoring NA's
func_paste <- function(x) paste(unique(x[!is.na(x)]), collapse = ", ")

# Confidence interval function
get_binCI <- function(x, n) as.numeric(setNames(binom.test(x, n)$conf.int * 100, c("lwr", "upr")))

# Corrects the gene names found in the "cluster" column
fix_gene_names <- function(df, plasmid = FALSE) {
  genes <- unique(df$ref_name)
  new_names <- gsub("^(.*?)\\..*", "\\1", genes)
  new_names <- gsub("_", "", new_names, fixed = T)
  new_names <- gsub("-", "", new_names, fixed = T)
  
  gene_names <- c()
  for (i in new_names) {
    p <-
      paste(tolower(substring(i, 1, 3)),
            substring(i, 4),
            sep = "",
            collapse = " ")
    gene_names <- c(gene_names, p)
  }
  df2 <- data.frame(genes, gene_names) %>%
    mutate(genes = as.character(genes)) %>%
    rename(ref_name = genes)
  
  if (plasmid == FALSE) {
    df %>%
      left_join(df2, by = "ref_name") %>%
      mutate(
        gene_names = as.character(gene_names),
        ref = gsub("(.*?)_amr_report.tsv", "\\1", ref)
      )
  } else {
    df %>%
      left_join(df2, by = "ref_name") %>%
      mutate(gene_names = as.character(gene_names),
             ref = gsub("(.*?)/report.tsv", "\\1", ref))
  }
}

# Allowed flags from the ARIBA report
acq_flags <- c(
  "27",
  "155",
  "411",
  "923",
  "795",
  "539",
  "667",
  "795"
)

int_flags <- c(
  "19",
  "27",
  "147",
  "155",
  "403",
  "411",
  "915",
  "923",
  "787",
  "795",
  "531",
  "539",
  "659",
  "667",
  "787",
  "795"
)

# Function that returns info on flag selection
check_flags <- function(df, acquired = TRUE) {
  if (acquired == TRUE) {
    df <- df %>%
      select(ref, gene_names, flag, ref_ctg_change) %>%
      mutate(flag_result = as.integer(flag %in% acq_flags)) %>%
      rename("gene" = gene_names)
  } else {
    df <- df %>%
      select(ref, gene_names, flag, ref_ctg_change) %>%
      mutate(flag_result = as.integer(flag %in% int_flags)) %>%
      rename("gene" = gene_names)
  }
  return(df)
}

# Generate overview table of acquired genes
create_table <- function(df, acquired = TRUE) {
  if (acquired == TRUE) {
    df <- df %>%
      select(ref, gene_names, flag, ref_ctg_change) %>%
      filter(flag %in% acq_flags) %>%
      mutate(id = 1:n()) %>%
      spread(gene_names, ref_ctg_change) %>%
      group_by(ref) %>%
      summarise_all(list(func_paste)) %>%
      select(-c(id, flag)) %>%
      gather(gene, result, -ref) %>%
      mutate(
        result_total = ifelse(result == "", 0, 1),
        result_total = as.character(result_total)
      ) %>%
      select(-result) %>%
      rename("result" = result_total)
  } else {
    df <- df %>%
      select(ref, gene_names, flag, ref_ctg_change) %>%
      filter(flag %in% int_flags) %>%
      mutate(id = 1:n()) %>%
      spread(gene_names, ref_ctg_change) %>%
      group_by(ref) %>%
      summarise_all(list(func_paste)) %>%
      select(-c(id, flag)) %>%
      gather(gene, mut, -ref) %>%
      mutate(
        mut = ifelse(mut == "" | mut == "." | is.na(mut) == TRUE, 0, mut),
        result = ifelse(mut != 0, 1, 0),
        result = as.integer(result)
      )
  }
  return(df)
}

# Function that returns a filtered dataframe based on the string "genes"
filter_table <- function(df) {
  report_genes <- unique(df$gene)
  grep_genes <- c()
  for (gene in genes) {
    for (g in report_genes) {
      if (grepl(gene, g, ignore.case = T) == TRUE) {
        grep_genes <- c(grep_genes, g)
      }
    }
  }
  df <- df %>%
    filter(gene %in% grep_genes) %>%
    mutate(gene = gsub("_", "", gene),
           gene = as.character(gene))
  return(df)
}

# calculates percentage of present/absent mutations and genes
calc_stats <- function(df) {
  df %>%
    group_by(gene, result) %>%
    count() %>%
    ungroup() %>%
    mutate(result = if_else(result == 1,
                            "Present",
                            "Absent")) %>%
    spread(result, n, fill = 0) %>%
    rowwise() %>%
    mutate(Absent = ifelse("Absent" %in% names(.), Absent, 0)) %>%
    mutate(
      Total = Present + Absent,
      Percent = round(Present / Total * 100, 1),
      lwr = round(get_binCI(Present, Total)[1], 1),
      upr = round(get_binCI(Present, Total)[2], 1)
    ) %>%
    ungroup()
}

create_report <- function(df, mut = FALSE) {
  if (mut == FALSE) {
    if ("mut" %in% names(df)) {
      df <- select(df, -mut)
    }
    df %>%
      group_by(ref) %>%
      mutate(id = 1:n()) %>%
      spread(gene, result) %>%
      summarise_all(list(func_paste)) %>%
      select(-id)
  } else {
    df %>%
      group_by(ref) %>%
      mutate(id = 1:n()) %>%
      spread(gene, mut) %>%
      summarise_all(list(func_paste)) %>%
      select(-c(id, result))
  }
}

# Corrects or mutations in QRDR for gyrA, gyrB, parC and parE genes.
# The function returns columns of 1/0 values for whether or not the 
# mutations reported by ARIBA is within the QRDR in the gene:
# gyrA: AA 67 - 106
# gyrB: AA 333 - 481
# ParC: AA 51 - 170
# parE: AA 366 - 523
# Source: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1142146/pdf/cjvr68pg229.pdf
fix_gyr_par_results <- function(df) {
  df %>%
    mutate(gyrA_result = mut %>% # control for mutation within QRDR for gyrA
             str_extract_all("\\d+") %>% # from reprex package
             map(as.integer) %>% # converts all to integer
             map_lgl(~ any(.x >= 67L & .x <= 106L)), # returns TRUE/FALSE whether value is within range or not
           gyrA_result = if_else(gene != "gyrA", NA, gyrA_result), # filters out results for all other genes
           gyrA_result = as.integer(gyrA_result),
           gyrB_result = mut %>% # control for mutation within QRDR for gyrB
             str_extract_all("\\d+") %>%
             map(as.integer) %>%
             map_lgl(~ any(.x >= 333L & .x <= 481L)),
           gyrB_result = if_else(gene != "gyrB", NA, gyrB_result),
           gyrB_result = as.integer(gyrB_result),
           parC_result = mut %>% # control for mutation within QRDR for parC
             str_extract_all("\\d+") %>% 
             map(as.integer) %>% 
             map_lgl(~ any(.x >= 51L & .x <= 170L)),
           parC_result = if_else(gene != "parC", NA, parC_result),
           parC_result = as.integer(parC_result),
           parE_result = mut %>% # control for mutation within QRDR for parE
             str_extract_all("\\d+") %>% 
             map(as.integer) %>% 
             map_lgl(~ any(.x >= 366L & .x <= 523L)),
           parE_result = if_else(gene != "parE", NA, parE_result),
           parE_result = as.integer(parE_result)) %>%
    mutate(result_gyr_par = case_when(gene == "gyrA" ~ gyrA_result,
                                      gene == "gyrB" ~ gyrB_result,
                                      gene == "parC" ~ parC_result,
                                      gene == "parE" ~ parE_result)) %>%
    mutate(result_total = ifelse(gene %in% c("gyrA","gyrB","parC","parE"),
                                 result_gyr_par, result)) %>%
    select(-c(gyrA_result,
              gyrB_result,
              parC_result,
              parE_result,
              result_gyr_par,
              result)) %>%
    rename("result" = result_total)
}
